repos:
  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.3
    hooks:
      - id: maven
        args: [ 'clean compile scalafmt:format --file pom.xml' ]
  - repo: local
    hooks:
      - id: copyright_checker
        name: copyright_checker
        entry: python ./hack/gen-copyright.py
        language: python
        files: \.(java|py|sh|scala)$