repos:
  -   repo: https://github.com/ejba/pre-commit-maven
      rev: v0.3.3
      hooks:
        -   id: maven
            args: ['clean compile --file pom.xml']
# TODO: Fix all issues in https://github.com/TUDB-Labs/TuDB/issues/99
#        -   id: maven-checkstyle
