site_name: TuDB - A Distributed Graph Database System
repo_url: https://github.com/TUDB-Labs/TuDB
strict: true
theme:
  name: readthedocs
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.jpg
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
nav:
  - Home: README.md
  - Getting Started:
      - examples/basic.md
  - Developer Guide:
      - CONTRIBUTING.md
      - protocol-services-interface-design.md
      - performance-report.md
  - Roadmap: roadmap.md
