name: pre-commit

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: self-hosted
    permissions:
       contents: write
       pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v3.0.0
        env:
          PRE_COMMIT_HOME: ~/.cache/pre-commit
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files}}
