name: pre-commit

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: self-hosted
    permissions:
       contents: write
       pull-requests: write
    steps:
      - uses: actions/checkout@v3
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
          RUNNER_TOOL_CACHE: /opt/hostedtoolcache
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '
      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: /home/gitRunner/.m2/settings.xml
      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: /home/gitRunner/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v3.0.0
        env:
          PRE_COMMIT_HOME: /home/gitRunner/pre-commit
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files}}
