name: pre-commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: self-hosted
    permissions:
       contents: write
       pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: /home/gitRunner/pre-commit
          key: pre-commit-3|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v3.0.0
        env:
          PRE_COMMIT_HOME: /home/gitRunner/pre-commit
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files}}
